apiVersion: apps/v1
kind: Deployment
metadata: 
  name: product-svc
  labels: 
    app: product-svc
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: product-svc
  template:
    metadata:
      labels:
        app: product-svc
    spec:
      containers: 
      - name: product-svc
        image: muhamedjasim/product-svc:latest
        ports:
        - containerPort: 50052
        env:
          - name: PORT
            value: ":50052"
          - name: DB_URL
            value: "postgres://cityvibe:jasi123@postgres-service:5432/product_svc"
          - name: JWT_SECRET_KEY
            value: "r343nfse84"

---

apiVersion: v1
kind: Service
metadata: 
  name: product-svc-service
spec:
  selector:
    app: product-svc
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052